-- The first community release shipped with a deliberately small set of schools.
-- Keep this directory data in Postgres so every school picker (sign-up,
-- settings, course creation, and community search) receives the same results.
insert into public.institutions (
  external_source,
  external_id,
  canonical_name,
  country_code,
  region_code,
  city,
  domain,
  aliases,
  default_time_zone
)
values
  -- Virginia
  ('manual', 'US-VA-UVA', 'University of Virginia', 'US', 'VA', 'Charlottesville', 'virginia.edu', array['UVA', 'Virginia'], 'America/New_York'),
  ('manual', 'US-VA-VT', 'Virginia Tech', 'US', 'VA', 'Blacksburg', 'vt.edu', array['Virginia Polytechnic Institute and State University', 'VPI', 'VT'], 'America/New_York'),
  ('manual', 'US-VA-WM', 'William & Mary', 'US', 'VA', 'Williamsburg', 'wm.edu', array['College of William and Mary', 'W&M'], 'America/New_York'),
  ('manual', 'US-VA-GMU', 'George Mason University', 'US', 'VA', 'Fairfax', 'gmu.edu', array['George Mason', 'GMU'], 'America/New_York'),
  ('manual', 'US-VA-VCU', 'Virginia Commonwealth University', 'US', 'VA', 'Richmond', 'vcu.edu', array['VCU'], 'America/New_York'),
  ('manual', 'US-VA-JMU', 'James Madison University', 'US', 'VA', 'Harrisonburg', 'jmu.edu', array['James Madison', 'JMU'], 'America/New_York'),
  ('manual', 'US-VA-ODU', 'Old Dominion University', 'US', 'VA', 'Norfolk', 'odu.edu', array['Old Dominion', 'ODU'], 'America/New_York'),
  ('manual', 'US-VA-LIBERTY', 'Liberty University', 'US', 'VA', 'Lynchburg', 'liberty.edu', array['Liberty'], 'America/New_York'),
  ('manual', 'US-VA-RICHMOND', 'University of Richmond', 'US', 'VA', 'Richmond', 'richmond.edu', array['Richmond'], 'America/New_York'),
  ('manual', 'US-VA-WLU', 'Washington and Lee University', 'US', 'VA', 'Lexington', 'wlu.edu', array['Washington and Lee', 'W&L'], 'America/New_York'),

  -- Additional U.S. research universities and widely attended institutions
  ('manual', 'US-RI-BROWN', 'Brown University', 'US', 'RI', 'Providence', 'brown.edu', array['Brown'], 'America/New_York'),
  ('manual', 'US-NH-DARTMOUTH', 'Dartmouth College', 'US', 'NH', 'Hanover', 'dartmouth.edu', array['Dartmouth'], 'America/New_York'),
  ('manual', 'US-CA-CALTECH', 'California Institute of Technology', 'US', 'CA', 'Pasadena', 'caltech.edu', array['Caltech'], 'America/Los_Angeles'),
  ('manual', 'US-MD-JHU', 'Johns Hopkins University', 'US', 'MD', 'Baltimore', 'jhu.edu', array['Johns Hopkins', 'JHU'], 'America/New_York'),
  ('manual', 'US-TN-VANDERBILT', 'Vanderbilt University', 'US', 'TN', 'Nashville', 'vanderbilt.edu', array['Vanderbilt', 'Vandy'], 'America/Chicago'),
  ('manual', 'US-TX-RICE', 'Rice University', 'US', 'TX', 'Houston', 'rice.edu', array['Rice'], 'America/Chicago'),
  ('manual', 'US-IN-NOTRE-DAME', 'University of Notre Dame', 'US', 'IN', 'Notre Dame', 'nd.edu', array['Notre Dame', 'ND'], 'America/Indiana/Indianapolis'),
  ('manual', 'US-DC-GEORGETOWN', 'Georgetown University', 'US', 'DC', 'Washington', 'georgetown.edu', array['Georgetown'], 'America/New_York'),
  ('manual', 'US-GA-EMORY', 'Emory University', 'US', 'GA', 'Atlanta', 'emory.edu', array['Emory'], 'America/New_York'),
  ('manual', 'US-MO-WUSTL', 'Washington University in St. Louis', 'US', 'MO', 'St. Louis', 'wustl.edu', array['WashU', 'WUSTL'], 'America/Chicago'),
  ('manual', 'US-MA-TUFTS', 'Tufts University', 'US', 'MA', 'Medford', 'tufts.edu', array['Tufts'], 'America/New_York'),
  ('manual', 'US-NC-UNC', 'University of North Carolina at Chapel Hill', 'US', 'NC', 'Chapel Hill', 'unc.edu', array['UNC', 'UNC Chapel Hill', 'Carolina'], 'America/New_York'),
  ('manual', 'US-NC-NCSU', 'North Carolina State University', 'US', 'NC', 'Raleigh', 'ncsu.edu', array['NC State', 'NCSU'], 'America/New_York'),
  ('manual', 'US-FL-UF', 'University of Florida', 'US', 'FL', 'Gainesville', 'ufl.edu', array['UF', 'Florida'], 'America/New_York'),
  ('manual', 'US-FL-FSU', 'Florida State University', 'US', 'FL', 'Tallahassee', 'fsu.edu', array['FSU', 'Florida State'], 'America/New_York'),
  ('manual', 'US-FL-MIAMI', 'University of Miami', 'US', 'FL', 'Coral Gables', 'miami.edu', array['UMiami', 'Miami'], 'America/New_York'),
  ('manual', 'US-FL-UCF', 'University of Central Florida', 'US', 'FL', 'Orlando', 'ucf.edu', array['UCF'], 'America/New_York'),
  ('manual', 'US-OH-OSU', 'The Ohio State University', 'US', 'OH', 'Columbus', 'osu.edu', array['Ohio State', 'OSU'], 'America/New_York'),
  ('manual', 'US-PA-PSU', 'Pennsylvania State University', 'US', 'PA', 'University Park', 'psu.edu', array['Penn State', 'PSU'], 'America/New_York'),
  ('manual', 'US-PA-PITT', 'University of Pittsburgh', 'US', 'PA', 'Pittsburgh', 'pitt.edu', array['Pitt'], 'America/New_York'),
  ('manual', 'US-OH-CWRU', 'Case Western Reserve University', 'US', 'OH', 'Cleveland', 'case.edu', array['Case Western', 'CWRU'], 'America/New_York'),
  ('manual', 'US-IN-PURDUE', 'Purdue University', 'US', 'IN', 'West Lafayette', 'purdue.edu', array['Purdue'], 'America/Indiana/Indianapolis'),
  ('manual', 'US-IN-IU', 'Indiana University Bloomington', 'US', 'IN', 'Bloomington', 'iu.edu', array['Indiana University', 'IU Bloomington', 'IU'], 'America/Indiana/Indianapolis'),
  ('manual', 'US-WI-UW', 'University of Wisconsin-Madison', 'US', 'WI', 'Madison', 'wisc.edu', array['UW Madison', 'Wisconsin'], 'America/Chicago'),
  ('manual', 'US-MN-UMN', 'University of Minnesota Twin Cities', 'US', 'MN', 'Minneapolis', 'umn.edu', array['University of Minnesota', 'UMN'], 'America/Chicago'),
  ('manual', 'US-IA-UIOWA', 'University of Iowa', 'US', 'IA', 'Iowa City', 'uiowa.edu', array['Iowa'], 'America/Chicago'),
  ('manual', 'US-IA-ISU', 'Iowa State University', 'US', 'IA', 'Ames', 'iastate.edu', array['Iowa State', 'ISU'], 'America/Chicago'),
  ('manual', 'US-CO-CU', 'University of Colorado Boulder', 'US', 'CO', 'Boulder', 'colorado.edu', array['CU Boulder', 'Colorado'], 'America/Denver'),
  ('manual', 'US-CO-CSU', 'Colorado State University', 'US', 'CO', 'Fort Collins', 'colostate.edu', array['Colorado State', 'CSU'], 'America/Denver'),
  ('manual', 'US-AZ-UA', 'University of Arizona', 'US', 'AZ', 'Tucson', 'arizona.edu', array['Arizona', 'UArizona'], 'America/Phoenix'),
  ('manual', 'US-AZ-ASU', 'Arizona State University', 'US', 'AZ', 'Tempe', 'asu.edu', array['Arizona State', 'ASU'], 'America/Phoenix'),
  ('manual', 'US-OR-UO', 'University of Oregon', 'US', 'OR', 'Eugene', 'uoregon.edu', array['Oregon', 'UO'], 'America/Los_Angeles'),
  ('manual', 'US-OR-OSU', 'Oregon State University', 'US', 'OR', 'Corvallis', 'oregonstate.edu', array['Oregon State', 'OSU'], 'America/Los_Angeles'),
  ('manual', 'US-WA-WSU', 'Washington State University', 'US', 'WA', 'Pullman', 'wsu.edu', array['Washington State', 'WSU'], 'America/Los_Angeles'),
  ('manual', 'US-CA-UCSD', 'University of California, San Diego', 'US', 'CA', 'La Jolla', 'ucsd.edu', array['UC San Diego', 'UCSD'], 'America/Los_Angeles'),
  ('manual', 'US-CA-UCSB', 'University of California, Santa Barbara', 'US', 'CA', 'Santa Barbara', 'ucsb.edu', array['UC Santa Barbara', 'UCSB'], 'America/Los_Angeles'),
  ('manual', 'US-CA-UCD', 'University of California, Davis', 'US', 'CA', 'Davis', 'ucdavis.edu', array['UC Davis', 'UCD'], 'America/Los_Angeles'),
  ('manual', 'US-CA-UCI', 'University of California, Irvine', 'US', 'CA', 'Irvine', 'uci.edu', array['UC Irvine', 'UCI'], 'America/Los_Angeles'),
  ('manual', 'US-CA-UCSC', 'University of California, Santa Cruz', 'US', 'CA', 'Santa Cruz', 'ucsc.edu', array['UC Santa Cruz', 'UCSC'], 'America/Los_Angeles'),
  ('manual', 'US-CA-UCR', 'University of California, Riverside', 'US', 'CA', 'Riverside', 'ucr.edu', array['UC Riverside', 'UCR'], 'America/Los_Angeles'),
  ('manual', 'US-CA-CALPOLY', 'California Polytechnic State University, San Luis Obispo', 'US', 'CA', 'San Luis Obispo', 'calpoly.edu', array['Cal Poly', 'Cal Poly SLO'], 'America/Los_Angeles'),
  ('manual', 'US-CA-SDSU', 'San Diego State University', 'US', 'CA', 'San Diego', 'sdsu.edu', array['San Diego State', 'SDSU'], 'America/Los_Angeles'),
  ('manual', 'US-CA-SJSU', 'San Jose State University', 'US', 'CA', 'San Jose', 'sjsu.edu', array['San Jose State', 'SJSU'], 'America/Los_Angeles'),
  ('manual', 'US-CA-SCU', 'Santa Clara University', 'US', 'CA', 'Santa Clara', 'scu.edu', array['Santa Clara', 'SCU'], 'America/Los_Angeles'),
  ('manual', 'US-CA-PEPPERDINE', 'Pepperdine University', 'US', 'CA', 'Malibu', 'pepperdine.edu', array['Pepperdine'], 'America/Los_Angeles'),
  ('manual', 'US-TX-TAMU', 'Texas A&M University', 'US', 'TX', 'College Station', 'tamu.edu', array['Texas A&M', 'TAMU'], 'America/Chicago'),
  ('manual', 'US-TX-BAYLOR', 'Baylor University', 'US', 'TX', 'Waco', 'baylor.edu', array['Baylor'], 'America/Chicago'),
  ('manual', 'US-TX-SMU', 'Southern Methodist University', 'US', 'TX', 'Dallas', 'smu.edu', array['SMU'], 'America/Chicago'),
  ('manual', 'US-TX-TCU', 'Texas Christian University', 'US', 'TX', 'Fort Worth', 'tcu.edu', array['TCU'], 'America/Chicago'),
  ('manual', 'US-TX-UTD', 'The University of Texas at Dallas', 'US', 'TX', 'Richardson', 'utdallas.edu', array['UT Dallas', 'UTD'], 'America/Chicago'),
  ('manual', 'US-TX-UH', 'University of Houston', 'US', 'TX', 'Houston', 'uh.edu', array['Houston', 'UH'], 'America/Chicago'),
  ('manual', 'US-TX-TTU', 'Texas Tech University', 'US', 'TX', 'Lubbock', 'ttu.edu', array['Texas Tech', 'TTU'], 'America/Chicago'),
  ('manual', 'US-GA-UGA', 'University of Georgia', 'US', 'GA', 'Athens', 'uga.edu', array['Georgia', 'UGA'], 'America/New_York'),
  ('manual', 'US-AL-AUBURN', 'Auburn University', 'US', 'AL', 'Auburn', 'auburn.edu', array['Auburn'], 'America/Chicago'),
  ('manual', 'US-AL-UA', 'The University of Alabama', 'US', 'AL', 'Tuscaloosa', 'ua.edu', array['Alabama', 'UA'], 'America/Chicago'),
  ('manual', 'US-TN-UTK', 'University of Tennessee, Knoxville', 'US', 'TN', 'Knoxville', 'utk.edu', array['Tennessee', 'UT Knoxville', 'UTK'], 'America/New_York'),
  ('manual', 'US-SC-CLEMSON', 'Clemson University', 'US', 'SC', 'Clemson', 'clemson.edu', array['Clemson'], 'America/New_York'),
  ('manual', 'US-SC-USC', 'University of South Carolina', 'US', 'SC', 'Columbia', 'sc.edu', array['South Carolina', 'UofSC'], 'America/New_York'),
  ('manual', 'US-MD-UMD', 'University of Maryland, College Park', 'US', 'MD', 'College Park', 'umd.edu', array['Maryland', 'UMD'], 'America/New_York'),
  ('manual', 'US-NJ-RUTGERS', 'Rutgers University-New Brunswick', 'US', 'NJ', 'New Brunswick', 'rutgers.edu', array['Rutgers', 'Rutgers New Brunswick'], 'America/New_York'),
  ('manual', 'US-MA-UMASS', 'University of Massachusetts Amherst', 'US', 'MA', 'Amherst', 'umass.edu', array['UMass Amherst', 'UMass'], 'America/New_York'),
  ('manual', 'US-CT-UCONN', 'University of Connecticut', 'US', 'CT', 'Storrs', 'uconn.edu', array['UConn', 'Connecticut'], 'America/New_York'),
  ('manual', 'US-NY-SYRACUSE', 'Syracuse University', 'US', 'NY', 'Syracuse', 'syr.edu', array['Syracuse'], 'America/New_York'),
  ('manual', 'US-NY-ROCHESTER', 'University of Rochester', 'US', 'NY', 'Rochester', 'rochester.edu', array['Rochester'], 'America/New_York'),
  ('manual', 'US-NY-RPI', 'Rensselaer Polytechnic Institute', 'US', 'NY', 'Troy', 'rpi.edu', array['RPI', 'Rensselaer'], 'America/New_York'),
  ('manual', 'US-NY-FORDHAM', 'Fordham University', 'US', 'NY', 'Bronx', 'fordham.edu', array['Fordham'], 'America/New_York'),
  ('manual', 'US-DC-GWU', 'George Washington University', 'US', 'DC', 'Washington', 'gwu.edu', array['George Washington', 'GWU', 'GW'], 'America/New_York'),
  ('manual', 'US-DC-AMERICAN', 'American University', 'US', 'DC', 'Washington', 'american.edu', array['American', 'AU'], 'America/New_York'),
  ('manual', 'US-DC-HOWARD', 'Howard University', 'US', 'DC', 'Washington', 'howard.edu', array['Howard'], 'America/New_York'),
  ('manual', 'US-DE-UDEL', 'University of Delaware', 'US', 'DE', 'Newark', 'udel.edu', array['Delaware', 'UD'], 'America/New_York'),
  ('manual', 'US-PA-TEMPLE', 'Temple University', 'US', 'PA', 'Philadelphia', 'temple.edu', array['Temple'], 'America/New_York'),
  ('manual', 'US-PA-DREXEL', 'Drexel University', 'US', 'PA', 'Philadelphia', 'drexel.edu', array['Drexel'], 'America/New_York'),
  ('manual', 'US-NJ-STEVENS', 'Stevens Institute of Technology', 'US', 'NJ', 'Hoboken', 'stevens.edu', array['Stevens'], 'America/New_York'),
  ('manual', 'US-NJ-NJIT', 'New Jersey Institute of Technology', 'US', 'NJ', 'Newark', 'njit.edu', array['NJIT'], 'America/New_York'),
  ('manual', 'US-MA-BC', 'Boston College', 'US', 'MA', 'Chestnut Hill', 'bc.edu', array['BC'], 'America/New_York'),
  ('manual', 'US-MA-BRANDEIS', 'Brandeis University', 'US', 'MA', 'Waltham', 'brandeis.edu', array['Brandeis'], 'America/New_York'),
  ('manual', 'US-MA-WPI', 'Worcester Polytechnic Institute', 'US', 'MA', 'Worcester', 'wpi.edu', array['WPI'], 'America/New_York'),
  ('manual', 'US-PA-LEHIGH', 'Lehigh University', 'US', 'PA', 'Bethlehem', 'lehigh.edu', array['Lehigh'], 'America/New_York'),
  ('manual', 'US-PA-VILLANOVA', 'Villanova University', 'US', 'PA', 'Villanova', 'villanova.edu', array['Villanova'], 'America/New_York'),
  ('manual', 'US-NC-WAKE', 'Wake Forest University', 'US', 'NC', 'Winston-Salem', 'wfu.edu', array['Wake Forest', 'WFU'], 'America/New_York'),
  ('manual', 'US-LA-TULANE', 'Tulane University', 'US', 'LA', 'New Orleans', 'tulane.edu', array['Tulane'], 'America/Chicago'),
  ('manual', 'US-LA-LSU', 'Louisiana State University', 'US', 'LA', 'Baton Rouge', 'lsu.edu', array['LSU'], 'America/Chicago'),
  ('manual', 'US-KS-KU', 'University of Kansas', 'US', 'KS', 'Lawrence', 'ku.edu', array['Kansas', 'KU'], 'America/Chicago'),
  ('manual', 'US-KS-KSU', 'Kansas State University', 'US', 'KS', 'Manhattan', 'k-state.edu', array['Kansas State', 'K-State'], 'America/Chicago'),
  ('manual', 'US-NE-UNL', 'University of Nebraska-Lincoln', 'US', 'NE', 'Lincoln', 'unl.edu', array['Nebraska', 'UNL'], 'America/Chicago'),
  ('manual', 'US-OK-OU', 'University of Oklahoma', 'US', 'OK', 'Norman', 'ou.edu', array['Oklahoma', 'OU'], 'America/Chicago'),
  ('manual', 'US-OK-OSU', 'Oklahoma State University', 'US', 'OK', 'Stillwater', 'okstate.edu', array['Oklahoma State', 'OSU'], 'America/Chicago'),
  ('manual', 'US-MO-MIZZOU', 'University of Missouri', 'US', 'MO', 'Columbia', 'missouri.edu', array['Missouri', 'Mizzou'], 'America/Chicago'),
  ('manual', 'US-AR-UARK', 'University of Arkansas', 'US', 'AR', 'Fayetteville', 'uark.edu', array['Arkansas', 'UArk'], 'America/Chicago'),
  ('manual', 'US-KY-UK', 'University of Kentucky', 'US', 'KY', 'Lexington', 'uky.edu', array['Kentucky', 'UK'], 'America/New_York'),
  ('manual', 'US-KY-LOUISVILLE', 'University of Louisville', 'US', 'KY', 'Louisville', 'louisville.edu', array['Louisville', 'UofL'], 'America/New_York'),
  ('manual', 'US-WV-WVU', 'West Virginia University', 'US', 'WV', 'Morgantown', 'wvu.edu', array['West Virginia', 'WVU'], 'America/New_York'),
  ('manual', 'US-UT-UU', 'University of Utah', 'US', 'UT', 'Salt Lake City', 'utah.edu', array['Utah', 'The U'], 'America/Denver'),
  ('manual', 'US-UT-BYU', 'Brigham Young University', 'US', 'UT', 'Provo', 'byu.edu', array['BYU'], 'America/Denver'),
  ('manual', 'US-ID-BSU', 'Boise State University', 'US', 'ID', 'Boise', 'boisestate.edu', array['Boise State', 'BSU'], 'America/Boise'),
  ('manual', 'US-NV-UNR', 'University of Nevada, Reno', 'US', 'NV', 'Reno', 'unr.edu', array['Nevada', 'UNR'], 'America/Los_Angeles'),
  ('manual', 'US-NV-UNLV', 'University of Nevada, Las Vegas', 'US', 'NV', 'Las Vegas', 'unlv.edu', array['UNLV'], 'America/Los_Angeles'),
  ('manual', 'US-NM-UNM', 'University of New Mexico', 'US', 'NM', 'Albuquerque', 'unm.edu', array['New Mexico', 'UNM'], 'America/Denver'),
  ('manual', 'US-NM-NMSU', 'New Mexico State University', 'US', 'NM', 'Las Cruces', 'nmsu.edu', array['New Mexico State', 'NMSU'], 'America/Denver'),
  ('manual', 'US-HI-UH', 'University of Hawaii at Manoa', 'US', 'HI', 'Honolulu', 'hawaii.edu', array['UH Manoa', 'University of Hawaii'], 'Pacific/Honolulu'),
  ('manual', 'US-AK-UAF', 'University of Alaska Fairbanks', 'US', 'AK', 'Fairbanks', 'uaf.edu', array['Alaska Fairbanks', 'UAF'], 'America/Anchorage'),
  ('manual', 'US-ME-UMAINE', 'University of Maine', 'US', 'ME', 'Orono', 'umaine.edu', array['Maine', 'UMaine'], 'America/New_York'),
  ('manual', 'US-VT-UVM', 'University of Vermont', 'US', 'VT', 'Burlington', 'uvm.edu', array['Vermont', 'UVM'], 'America/New_York'),
  ('manual', 'US-NH-UNH', 'University of New Hampshire', 'US', 'NH', 'Durham', 'unh.edu', array['New Hampshire', 'UNH'], 'America/New_York'),
  ('manual', 'US-RI-URI', 'University of Rhode Island', 'US', 'RI', 'Kingston', 'uri.edu', array['Rhode Island', 'URI'], 'America/New_York'),

  -- U.S. liberal arts colleges with broad national enrollment
  ('manual', 'US-MA-AMHERST', 'Amherst College', 'US', 'MA', 'Amherst', 'amherst.edu', array['Amherst'], 'America/New_York'),
  ('manual', 'US-MA-WILLIAMS', 'Williams College', 'US', 'MA', 'Williamstown', 'williams.edu', array['Williams'], 'America/New_York'),
  ('manual', 'US-PA-SWARTHMORE', 'Swarthmore College', 'US', 'PA', 'Swarthmore', 'swarthmore.edu', array['Swarthmore'], 'America/New_York'),
  ('manual', 'US-CA-POMONA', 'Pomona College', 'US', 'CA', 'Claremont', 'pomona.edu', array['Pomona'], 'America/Los_Angeles'),
  ('manual', 'US-MA-WELLESLEY', 'Wellesley College', 'US', 'MA', 'Wellesley', 'wellesley.edu', array['Wellesley'], 'America/New_York'),
  ('manual', 'US-ME-BOWDOIN', 'Bowdoin College', 'US', 'ME', 'Brunswick', 'bowdoin.edu', array['Bowdoin'], 'America/New_York'),
  ('manual', 'US-VT-MIDDLEBURY', 'Middlebury College', 'US', 'VT', 'Middlebury', 'middlebury.edu', array['Middlebury'], 'America/New_York'),
  ('manual', 'US-CT-WESLEYAN', 'Wesleyan University', 'US', 'CT', 'Middletown', 'wesleyan.edu', array['Wesleyan'], 'America/New_York'),
  ('manual', 'US-NY-COLGATE', 'Colgate University', 'US', 'NY', 'Hamilton', 'colgate.edu', array['Colgate'], 'America/New_York'),
  ('manual', 'US-NY-HAMILTON', 'Hamilton College', 'US', 'NY', 'Clinton', 'hamilton.edu', array['Hamilton'], 'America/New_York'),
  ('manual', 'US-NY-VASSAR', 'Vassar College', 'US', 'NY', 'Poughkeepsie', 'vassar.edu', array['Vassar'], 'America/New_York'),
  ('manual', 'US-PA-HAVERFORD', 'Haverford College', 'US', 'PA', 'Haverford', 'haverford.edu', array['Haverford'], 'America/New_York'),
  ('manual', 'US-NY-BARNARD', 'Barnard College', 'US', 'NY', 'New York', 'barnard.edu', array['Barnard'], 'America/New_York'),
  ('manual', 'US-CA-HMC', 'Harvey Mudd College', 'US', 'CA', 'Claremont', 'hmc.edu', array['Harvey Mudd', 'HMC'], 'America/Los_Angeles'),
  ('manual', 'US-CA-CMC', 'Claremont McKenna College', 'US', 'CA', 'Claremont', 'cmc.edu', array['Claremont McKenna', 'CMC'], 'America/Los_Angeles'),

  -- Additional Canadian universities, colleges, and polytechnics
  ('manual', 'CA-ON-YORK', 'York University', 'CA', 'ON', 'Toronto', 'yorku.ca', array['YorkU', 'York'], 'America/Toronto'),
  ('manual', 'CA-ON-TMU', 'Toronto Metropolitan University', 'CA', 'ON', 'Toronto', 'torontomu.ca', array['TMU', 'Ryerson University', 'Ryerson'], 'America/Toronto'),
  ('manual', 'CA-AB-CALGARY', 'University of Calgary', 'CA', 'AB', 'Calgary', 'ucalgary.ca', array['UCalgary', 'Calgary'], 'America/Edmonton'),
  ('manual', 'CA-QC-CONCORDIA', 'Concordia University', 'CA', 'QC', 'Montreal', 'concordia.ca', array['Concordia'], 'America/Toronto'),
  ('manual', 'CA-QC-UMONTREAL', 'Université de Montréal', 'CA', 'QC', 'Montreal', 'umontreal.ca', array['University of Montreal', 'UdeM'], 'America/Toronto'),
  ('manual', 'CA-QC-LAVAL', 'Université Laval', 'CA', 'QC', 'Quebec City', 'ulaval.ca', array['Laval University', 'Laval'], 'America/Toronto'),
  ('manual', 'CA-QC-SHERBROOKE', 'Université de Sherbrooke', 'CA', 'QC', 'Sherbrooke', 'usherbrooke.ca', array['University of Sherbrooke', 'UdeS'], 'America/Toronto'),
  ('manual', 'CA-NS-DAL', 'Dalhousie University', 'CA', 'NS', 'Halifax', 'dal.ca', array['Dalhousie', 'Dal'], 'America/Halifax'),
  ('manual', 'CA-BC-UVIC', 'University of Victoria', 'CA', 'BC', 'Victoria', 'uvic.ca', array['UVic', 'Victoria'], 'America/Vancouver'),
  ('manual', 'CA-MB-MANITOBA', 'University of Manitoba', 'CA', 'MB', 'Winnipeg', 'umanitoba.ca', array['UManitoba', 'Manitoba'], 'America/Winnipeg'),
  ('manual', 'CA-SK-USASK', 'University of Saskatchewan', 'CA', 'SK', 'Saskatoon', 'usask.ca', array['USask', 'Saskatchewan'], 'America/Regina'),
  ('manual', 'CA-ON-GUELPH', 'University of Guelph', 'CA', 'ON', 'Guelph', 'uoguelph.ca', array['Guelph', 'U of G'], 'America/Toronto'),
  ('manual', 'CA-ON-CARLETON', 'Carleton University', 'CA', 'ON', 'Ottawa', 'carleton.ca', array['Carleton'], 'America/Toronto'),
  ('manual', 'CA-NL-MUN', 'Memorial University of Newfoundland', 'CA', 'NL', 'St. Johns', 'mun.ca', array['Memorial University', 'MUN'], 'America/St_Johns'),
  ('manual', 'CA-NB-UNB', 'University of New Brunswick', 'CA', 'NB', 'Fredericton', 'unb.ca', array['UNB'], 'America/Moncton'),
  ('manual', 'CA-ON-WINDSOR', 'University of Windsor', 'CA', 'ON', 'Windsor', 'uwindsor.ca', array['UWindsor', 'Windsor'], 'America/Toronto'),
  ('manual', 'CA-ON-LAURIER', 'Wilfrid Laurier University', 'CA', 'ON', 'Waterloo', 'wlu.ca', array['Laurier', 'WLU'], 'America/Toronto'),
  ('manual', 'CA-ON-BROCK', 'Brock University', 'CA', 'ON', 'St. Catharines', 'brocku.ca', array['Brock'], 'America/Toronto'),
  ('manual', 'CA-ON-ONTARIO-TECH', 'Ontario Tech University', 'CA', 'ON', 'Oshawa', 'ontariotechu.ca', array['Ontario Tech', 'UOIT'], 'America/Toronto'),
  ('manual', 'CA-ON-TRENT', 'Trent University', 'CA', 'ON', 'Peterborough', 'trentu.ca', array['Trent'], 'America/Toronto'),
  ('manual', 'CA-SK-REGINA', 'University of Regina', 'CA', 'SK', 'Regina', 'uregina.ca', array['URegina', 'Regina'], 'America/Regina'),
  ('manual', 'CA-NS-ACADIA', 'Acadia University', 'CA', 'NS', 'Wolfville', 'acadiau.ca', array['Acadia'], 'America/Halifax'),
  ('manual', 'CA-NB-MTA', 'Mount Allison University', 'CA', 'NB', 'Sackville', 'mta.ca', array['Mount Allison', 'MtA'], 'America/Moncton'),
  ('manual', 'CA-NS-SMU', 'Saint Marys University', 'CA', 'NS', 'Halifax', 'smu.ca', array['Saint Marys', 'SMU Halifax'], 'America/Halifax'),
  ('manual', 'CA-NS-STFX', 'St. Francis Xavier University', 'CA', 'NS', 'Antigonish', 'stfx.ca', array['StFX', 'St Francis Xavier'], 'America/Halifax'),
  ('manual', 'CA-BC-UNBC', 'University of Northern British Columbia', 'CA', 'BC', 'Prince George', 'unbc.ca', array['UNBC'], 'America/Vancouver'),
  ('manual', 'CA-ON-LAKEHEAD', 'Lakehead University', 'CA', 'ON', 'Thunder Bay', 'lakeheadu.ca', array['Lakehead'], 'America/Toronto'),
  ('manual', 'CA-ON-LAURENTIAN', 'Laurentian University', 'CA', 'ON', 'Sudbury', 'laurentian.ca', array['Laurentian'], 'America/Toronto'),
  ('manual', 'CA-QC-UQAM', 'Université du Québec à Montréal', 'CA', 'QC', 'Montreal', 'uqam.ca', array['University of Quebec at Montreal', 'UQAM'], 'America/Toronto'),
  ('manual', 'CA-QC-ETS', 'École de technologie supérieure', 'CA', 'QC', 'Montreal', 'etsmtl.ca', array['ETS Montreal', 'ÉTS'], 'America/Toronto'),
  ('manual', 'CA-QC-HEC', 'HEC Montréal', 'CA', 'QC', 'Montreal', 'hec.ca', array['HEC Montreal', 'HEC'], 'America/Toronto'),
  ('manual', 'CA-QC-POLYMTL', 'Polytechnique Montréal', 'CA', 'QC', 'Montreal', 'polymtl.ca', array['Polytechnique Montreal'], 'America/Toronto'),
  ('manual', 'CA-MB-UWINNIPEG', 'University of Winnipeg', 'CA', 'MB', 'Winnipeg', 'uwinnipeg.ca', array['UWinnipeg', 'Winnipeg'], 'America/Winnipeg'),
  ('manual', 'CA-AB-MRU', 'Mount Royal University', 'CA', 'AB', 'Calgary', 'mtroyal.ca', array['Mount Royal', 'MRU'], 'America/Edmonton'),
  ('manual', 'CA-AB-MACEWAN', 'MacEwan University', 'CA', 'AB', 'Edmonton', 'macewan.ca', array['MacEwan'], 'America/Edmonton'),
  ('manual', 'CA-AB-LETHBRIDGE', 'University of Lethbridge', 'CA', 'AB', 'Lethbridge', 'ulethbridge.ca', array['ULethbridge', 'Lethbridge'], 'America/Edmonton'),
  ('manual', 'CA-BC-VIU', 'Vancouver Island University', 'CA', 'BC', 'Nanaimo', 'viu.ca', array['VIU'], 'America/Vancouver'),
  ('manual', 'CA-BC-KPU', 'Kwantlen Polytechnic University', 'CA', 'BC', 'Surrey', 'kpu.ca', array['Kwantlen', 'KPU'], 'America/Vancouver'),
  ('manual', 'CA-BC-BCIT', 'British Columbia Institute of Technology', 'CA', 'BC', 'Burnaby', 'bcit.ca', array['BCIT'], 'America/Vancouver'),
  ('manual', 'CA-AB-SAIT', 'Southern Alberta Institute of Technology', 'CA', 'AB', 'Calgary', 'sait.ca', array['SAIT'], 'America/Edmonton'),
  ('manual', 'CA-AB-NAIT', 'Northern Alberta Institute of Technology', 'CA', 'AB', 'Edmonton', 'nait.ca', array['NAIT'], 'America/Edmonton'),
  ('manual', 'CA-ON-ALGONQUIN', 'Algonquin College', 'CA', 'ON', 'Ottawa', 'algonquincollege.com', array['Algonquin'], 'America/Toronto'),
  ('manual', 'CA-ON-SENECA', 'Seneca Polytechnic', 'CA', 'ON', 'Toronto', 'senecapolytechnic.ca', array['Seneca College', 'Seneca'], 'America/Toronto'),
  ('manual', 'CA-ON-HUMBER', 'Humber Polytechnic', 'CA', 'ON', 'Toronto', 'humber.ca', array['Humber College', 'Humber'], 'America/Toronto'),
  ('manual', 'CA-ON-GEORGE-BROWN', 'George Brown College', 'CA', 'ON', 'Toronto', 'georgebrown.ca', array['George Brown', 'GBC'], 'America/Toronto'),
  ('manual', 'CA-ON-SHERIDAN', 'Sheridan College', 'CA', 'ON', 'Oakville', 'sheridancollege.ca', array['Sheridan'], 'America/Toronto')
on conflict (external_source, external_id) do update
set canonical_name = excluded.canonical_name,
    country_code = excluded.country_code,
    region_code = excluded.region_code,
    city = excluded.city,
    domain = excluded.domain,
    aliases = excluded.aliases,
    default_time_zone = excluded.default_time_zone,
    is_active = true;
